import js from '@eslint/js';
import tseslint from 'typescript-eslint';
import globals from 'globals';

/**
 * Lint rules, chosen to catch defects rather than to argue about style.
 *
 * Formatting is Prettier's job and is deliberately absent here — a lint run
 * that fails on a missing space trains people to stop reading lint output,
 * which is how the rules that matter get ignored too.
 *
 * The type-aware rules are the reason this exists at all. `no-floating-
 * promises` alone would have caught a whole class of bug this codebase is
 * exposed to: an un-awaited write that appears to succeed, reports success to
 * the person, and silently loses what they wrote.
 */
export default tseslint.config(
  {
    ignores: [
      '**/dist/**',
      '**/.next/**',
      '**/node_modules/**',
      '**/.expo/**',
      // Regenerated by Next on every build, with a triple-slash reference we do
      // not control.
      'apps/web/next-env.d.ts',
      '**/coverage/**',
      // Generated by Expo and not ours to lint.
      'apps/mobile/babel.config.js',
    ],
  },

  js.configs.recommended,
  ...tseslint.configs.recommendedTypeChecked,

  {
    languageOptions: {
      parserOptions: {
        // A dedicated project view rather than the build configs: those exclude
        // test files so they never reach `dist`, and a test file is exactly
        // where the type-aware rules earn their keep.
        project: './tsconfig.eslint.json',
        tsconfigRootDir: import.meta.dirname,
      },
      globals: { ...globals.node, ...globals.browser },
    },
    rules: {
      // The ones that find real bugs.
      '@typescript-eslint/no-floating-promises': 'error',
      '@typescript-eslint/await-thenable': 'error',
      '@typescript-eslint/no-misused-promises': 'error',
      'no-constant-binary-expression': 'error',
      // `require-atomic-updates` is off, and this is a decision rather than an
      // omission. It fired three times and all three were false positives: two
      // on state that is scoped to a single request or to shutdown, and one on
      // a local reassigned across an await inside one function. The rule cannot
      // see request scoping, so on a server like this it reports noise at
      // exactly the rate that trains people to stop reading lint output.

      // An unused variable is usually a half-finished edit. An argument that is
      // deliberately unused is spelled with a leading underscore.
      '@typescript-eslint/no-unused-vars': [
        'error',
        { argsIgnorePattern: '^_', varsIgnorePattern: '^_', caughtErrors: 'none' },
      ],

      // `any` is a real signal, but it is not a build-breaker on its own and
      // there are places where a cast is the honest answer.
      '@typescript-eslint/no-explicit-any': 'warn',
      '@typescript-eslint/no-unsafe-assignment': 'off',
      '@typescript-eslint/no-unsafe-member-access': 'off',
      '@typescript-eslint/no-unsafe-argument': 'off',
      '@typescript-eslint/no-unsafe-call': 'off',
      '@typescript-eslint/no-unsafe-return': 'off',
      // Template literals carrying numbers and booleans are fine and pervasive.
      '@typescript-eslint/restrict-template-expressions': 'off',
      '@typescript-eslint/no-non-null-assertion': 'off',
      '@typescript-eslint/require-await': 'off',
    },
  },

  {
    // Tests assert on rejected promises and deliberately construct bad input.
    files: ['**/*.test.ts', '**/*.test.tsx', '**/e2e/**'],
    rules: {
      '@typescript-eslint/no-floating-promises': 'off',
      '@typescript-eslint/no-unsafe-assignment': 'off',
    },
  },

  {
    // Plain JS with no type information behind it.
    files: ['**/*.mjs', '**/*.js'],
    ...tseslint.configs.disableTypeChecked,
  },
);
